// <auto-generated />
using System;
using Entity.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models.Implements.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPlantId");

                    b.ToTable("Notification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Level = "info",
                            Message = "El sensor DEV-001 se ha conectado correctamente.",
                            Title = "Sensor conectado",
                            UserPlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Level = "warning",
                            Message = "La humedad del suelo cayó por debajo del 30%.",
                            Title = "Baja humedad detectada",
                            UserPlantId = 2
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.PlantCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlantCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plantas con hojas carnosas que almacenan agua.",
                            IsDeleted = false,
                            Name = "Suculentas"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plantas leñosas de tamaño medio.",
                            IsDeleted = false,
                            Name = "Arbustos"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Árboles que producen frutos comestibles.",
                            IsDeleted = false,
                            Name = "Árboles frutales"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plantas cultivadas por la belleza de sus flores.",
                            IsDeleted = false,
                            Name = "Flores ornamentales"
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.PlantSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("OptPHMax")
                        .HasColumnType("real");

                    b.Property<float>("OptPHMin")
                        .HasColumnType("real");

                    b.Property<float>("OptSoliMoistureMax")
                        .HasColumnType("real");

                    b.Property<float>("OptSoliMoistureMin")
                        .HasColumnType("real");

                    b.Property<float>("OptSolilTempMax")
                        .HasColumnType("real");

                    b.Property<float>("OptSolilTempMin")
                        .HasColumnType("real");

                    b.Property<int>("PlantCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantCategoryId");

                    b.ToTable("PlantSpecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CommonName = "Aloe Vera",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OptPHMax = 7.5f,
                            OptPHMin = 6f,
                            OptSoliMoistureMax = 50f,
                            OptSoliMoistureMin = 30f,
                            OptSolilTempMax = 27f,
                            OptSolilTempMin = 18f,
                            PlantCategoryId = 1,
                            ScientificName = "Aloe barbadensis miller"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CommonName = "Romero",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OptPHMax = 7.5f,
                            OptPHMin = 6f,
                            OptSoliMoistureMax = 60f,
                            OptSoliMoistureMin = 40f,
                            OptSolilTempMax = 30f,
                            OptSolilTempMin = 15f,
                            PlantCategoryId = 2,
                            ScientificName = "Salvia rosmarinus"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            CommonName = "Mango",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OptPHMax = 7.5f,
                            OptPHMin = 5.5f,
                            OptSoliMoistureMax = 70f,
                            OptSoliMoistureMin = 50f,
                            OptSolilTempMax = 35f,
                            OptSolilTempMin = 20f,
                            PlantCategoryId = 3,
                            ScientificName = "Mangifera indica"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            CommonName = "Rosa",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            OptPHMax = 6.8f,
                            OptPHMin = 6f,
                            OptSoliMoistureMax = 70f,
                            OptSoliMoistureMin = 40f,
                            OptSolilTempMax = 28f,
                            OptSolilTempMin = 15f,
                            PlantCategoryId = 4,
                            ScientificName = "Rosa gallica"
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.SensorDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<float>("BatteryLevel")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SensorDevice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            BatteryLevel = 95f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceId = "DEV-001",
                            IsDeleted = false,
                            LastSeenAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Model = "SoilSense v1",
                            Status = "online"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            BatteryLevel = 85f,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceId = "DEV-002",
                            IsDeleted = false,
                            LastSeenAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Model = "SoilSense v1",
                            Status = "offline"
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("PH")
                        .HasColumnType("real");

                    b.Property<int>("SensorDeviceId")
                        .HasColumnType("int");

                    b.Property<float>("SoilMoisture")
                        .HasColumnType("real");

                    b.Property<float>("SoilTemperature")
                        .HasColumnType("real");

                    b.Property<int>("UserPlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SensorDeviceId");

                    b.HasIndex("UserPlantId");

                    b.ToTable("sensorReading");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PH = 6.5f,
                            SensorDeviceId = 1,
                            SoilMoisture = 45f,
                            SoilTemperature = 24f,
                            UserPlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 10, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PH = 6.8f,
                            SensorDeviceId = 2,
                            SoilMoisture = 35f,
                            SoilTemperature = 26f,
                            UserPlantId = 2
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@smartagro.com",
                            IsDeleted = false,
                            Password = "admin123",
                            Role = "Administrator",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@smartagro.com",
                            IsDeleted = false,
                            Password = "demo123",
                            Role = "User",
                            Username = "demo"
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.UserPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantSpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("SensorDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantSpeciesId");

                    b.HasIndex("SensorDeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Nickname = "Mi Aloe",
                            PlantSpeciesId = 1,
                            SensorDeviceId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Nickname = "Mango Dulce",
                            PlantSpeciesId = 3,
                            SensorDeviceId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Entity.Models.Implements.Notification", b =>
                {
                    b.HasOne("Entity.Models.Implements.User", null)
                        .WithMany("notifications")
                        .HasForeignKey("UserId");

                    b.HasOne("Entity.Models.Implements.UserPlant", "UserPlant")
                        .WithMany("notifications")
                        .HasForeignKey("UserPlantId");

                    b.Navigation("UserPlant");
                });

            modelBuilder.Entity("Entity.Models.Implements.PlantSpecies", b =>
                {
                    b.HasOne("Entity.Models.Implements.PlantCategory", "PlantCategory")
                        .WithMany("plantSpecies")
                        .HasForeignKey("PlantCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantCategory");
                });

            modelBuilder.Entity("Entity.Models.Implements.SensorReading", b =>
                {
                    b.HasOne("Entity.Models.Implements.SensorDevice", "SensorDevice")
                        .WithMany("sensorReadings")
                        .HasForeignKey("SensorDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entity.Models.Implements.UserPlant", "UserPlant")
                        .WithMany("SensorReadings")
                        .HasForeignKey("UserPlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SensorDevice");

                    b.Navigation("UserPlant");
                });

            modelBuilder.Entity("Entity.Models.Implements.UserPlant", b =>
                {
                    b.HasOne("Entity.Models.Implements.PlantSpecies", "PlantSpecies")
                        .WithMany("userPlants")
                        .HasForeignKey("PlantSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Implements.SensorDevice", "SensorDevice")
                        .WithMany("userPlants")
                        .HasForeignKey("SensorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.Implements.User", "User")
                        .WithMany("userPlants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantSpecies");

                    b.Navigation("SensorDevice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Models.Implements.PlantCategory", b =>
                {
                    b.Navigation("plantSpecies");
                });

            modelBuilder.Entity("Entity.Models.Implements.PlantSpecies", b =>
                {
                    b.Navigation("userPlants");
                });

            modelBuilder.Entity("Entity.Models.Implements.SensorDevice", b =>
                {
                    b.Navigation("sensorReadings");

                    b.Navigation("userPlants");
                });

            modelBuilder.Entity("Entity.Models.Implements.User", b =>
                {
                    b.Navigation("notifications");

                    b.Navigation("userPlants");
                });

            modelBuilder.Entity("Entity.Models.Implements.UserPlant", b =>
                {
                    b.Navigation("SensorReadings");

                    b.Navigation("notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
